import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

import * as stylex from '@stylexjs/stylex';

const styles = stylex.create({
  body: {
    padding: '2rem',
    margin: 0,
  },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body {...stylex.props(styles.body)}>
        {children}
      </body>
    </html>
  );
}
